### ISSUE TITLE
未注册Activity目录问题

### ISSUE THREAD

**Issue by wangpingtaohn** [BolexLiu/AndroidHookStartActivity#1]
OtherActivity只能放在根目录(com.bolex.androidhookstartactivity)下，放到其他目录就报错：
have you declared this activity in your AndroidManifest.xml?
原因在于：HookInvationHandler类中invoke方法里的以下代码：
String PackageName = mProxyActivity.getPackage().getName();
ComponentName componentName = new ComponentName(PackageName, mOriginallyActivity.getName());
这行代码，getpackage().getName()获取的是该Activity的路径，而Component第一个参数是应用的包名，所以才会包该错。

**Comment by hehaobing2** [comment]
不是，应该是PackageManagerHandler的
new ComponentName(HookTargetActivity.class.getPackage().getName(), HookActivity.class.getName());的问题，ComponentName第一个参数改成应用的包名就可以了

**Comment by wangpingtaohn** [comment]
@hehaobing2 嗯嗯，这个也需要改，不过PackageManagerHandler这个是兼容AppCompatActivity的，如果Activity集成的是android.app.Activity，就不会调用它的invoke方法了。

**Comment by shouzhong** [comment]
我想问下这里一个可以关联多个吗

**Comment by BolexLiu** [comment]
这个bug已经被修复了 : ) #3
