### ISSUE TITLE
按Back键退出程序再进入就失效了

### ISSUE THREAD

**Issue by Yuyang1257312385** [BolexLiu/AndroidHookStartActivity#2]
进入app,点击启动，打开的是OtherActivity,
然后一直按back键退出程序，再次 进入app,点击启动，跳转的是HostActivity

**Comment by ngstyle** [comment]
Application 未销毁导致多次hook

**Comment by BolexLiu** [comment]
@ngstyle 谢谢了，最近在忙别的事，没来得及看issues
